//! Autogenerated weights for pallet_estate_executor
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//!
//! **NOTE**: These weights are placeholder estimates.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_estate_executor.
pub trait WeightInfo {
	fn create_will() -> Weight;
	fn heartbeat() -> Weight;
	fn execute_will() -> Weight;
	fn cancel() -> Weight;
}

/// Weights for pallet_estate_executor using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_will() -> Weight {
		Weight::from_parts(20_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	fn heartbeat() -> Weight {
		Weight::from_parts(15_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	fn execute_will() -> Weight {
		Weight::from_parts(20_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	fn cancel() -> Weight {
		Weight::from_parts(15_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_will() -> Weight {
		Weight::from_parts(20_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	fn heartbeat() -> Weight {
		Weight::from_parts(15_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn execute_will() -> Weight {
		Weight::from_parts(20_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn cancel() -> Weight {
		Weight::from_parts(15_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
